name: Nightly Build
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  workflow_dispatch:

jobs:
  build:
    name: Nightly Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'
      - name: Install the project
        run: uv sync --all-extras --dev --pre
      - name: Generate new Brick ontology
        # generate new Brick ontology (in case this hasn't been run)
        run: |
          uv run make
          cat Brick.ttl
      - name: zip imports and extensions
        run: |
          zip -r imports.zip imports
          zip -r extensions.zip extensions
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          automatic_release_tag: nightly
          title: Nightly Build ${{ steps.date.outputs.date }}
          files: |
            Brick.ttl
            Brick+imports.ttl
            Brick+extensions.ttl
            Brick-only.ttl
            imports.zip
            extensions.zip
